{"data_mtime": 1589170500, "dep_lines": [1, 1, 1], "dep_prios": [5, 30, 30], "dependencies": ["builtins", "abc", "typing"], "hash": "1d36a88d12fa2950150ea58c565e3963147243f4ea31de346445d55b9551403f", "id": "lib.exception.Module", "ignore_all": false, "interface_hash": "176122fc8436949d2bf182c01c1f8389f166e0a12e0a4e4d567b4fbf38e6351f", "mtime": 1589081679, "options": {"allow_redefinition": false, "allow_untyped_globals": false, "always_false": [], "always_true": [], "bazel": false, "check_untyped_defs": false, "disallow_any_decorated": false, "disallow_any_explicit": false, "disallow_any_expr": false, "disallow_any_generics": false, "disallow_any_unimported": false, "disallow_incomplete_defs": false, "disallow_subclassing_any": false, "disallow_untyped_calls": false, "disallow_untyped_decorators": false, "disallow_untyped_defs": false, "follow_imports": "silent", "follow_imports_for_stubs": false, "ignore_errors": false, "ignore_missing_imports": false, "implicit_reexport": true, "local_partial_types": false, "mypyc": false, "no_implicit_optional": false, "platform": "linux", "plugins": [], "show_none_errors": true, "strict_equality": false, "strict_optional": true, "strict_optional_whitelist": null, "warn_no_return": true, "warn_return_any": false, "warn_unreachable": false, "warn_unused_ignores": false}, "path": "/home/darkcode/Documents/thg/thg-framework/lib/exception/Module.py", "plugin_data": null, "size": 100, "suppressed": [], "version_id": "0.770"}